# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RingoTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RingoTalk
  
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'FirebaseFirestoreSwift'
  
  pod 'RealmSwift'
  
  pod 'Gallery'
  pod 'SKPhotoBrowser'
  pod 'SDWebImage'
  pod 'ProgressHUD'
  
  pod 'MessageKit'
  pod 'InputBarAccessoryView'
  
end
